const SAVE_OPERATION = 'SAVE_OPERATION';
const DELETE_EXPRESSION = 'DELETE_EXPRESSION';
const DELETE_ALL_EXPRESSIONS = 'DELETE_ALL_EXPRESSIONS';
const EDIT_EXPRESSION = 'EDIT_EXPRESSION';
const REMEMBER_USER_NAME = 'REMEMBER_USER_NAME';

export {SAVE_OPERATION , DELETE_ALL_EXPRESSIONS, DELETE_EXPRESSION, EDIT_EXPRESSION, REMEMBER_USER_NAME };